language: node_js

node_js:
  - 10.8

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

env:
  - CYPRESS_video=false
  - CYPRESS_RECORD_KEY=$RECORD_KEY

install:
  - npm ci

before_script:
  - echo $RECORD_KEY
  - npm run prod
  - npm start -- --silent &

script:
  - npm run lint
  - ./node_modules/.bin/cypress run --reporter cypress-image-snapshot/reporter --record -key RECORD_KEY
