language: node_js

node_js:
  - 10.8

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

env:
  - CYPRESS_video=false
  - CYPRESS_RECORD_KEY=$RECORD_KEY

install:
  - npm ci

before_script:
  - npm run prod
  - npm start -- --silent &

script:
  - npm run lint
  - npm run cypress:run
