language: node_js
dist: xenial
services:
  - xvfb

node_js:
  - 10.8

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

env:
  global:
    - CYPRESS_video=false

install:
  - npm ci

before_script:
  - npm run prod
  - 'export DISPLAY=:1'
  - npm start -- --silent &

script:
  - npm run lint
  - xvfb-run --server-args="-screen 0 1280x1024x8"
  - npm run cypress:run
