version: '3'
services:
  database:
    image: "mongo"
    container_name: 'lit-mongo'        
    volumes:            
      - ./data/db:/var/lib/mongo/data
    ports:
      - 27017:27017    
    command: mongod